name: Build development version

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout shared actions
        uses: actions/checkout@v3
        with:
          repository: 'andrii-aheiev/actions'
          ssh-key: '${{ secrets.SHARED_ACTIONS_KEY }}'
