name: Build development version

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout shared actions
        uses: actions/checkout@v3
