name: Build development version

on:
  push:
    branches:
      - develop
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: checkout shared actions
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.SHARED_ACTIONS_REPO }}
          ssh-key: ${{ secrets.SHARED_ACTIONS_KEY }}
          path: shared

      - name: Use shared action
        uses: ./shared/actions/jdk11
